### ISSUE TITLE
Those #@$%ing JSON numerics!

### ISSUE THREAD

**Issue by predictiple** [Velocidex/evtx#9] opened 2019-11-26 19:41 UTC
I understand that it's *technically* correct to preserve the field typing from the source but it presents some post-processing hazards. In my Logstash post-processing, fields such as `Keywords` when represented as an astronomical-scale integer have to be first coerced to a float and then to a string to avoid breaking the limits of their string->int conversion code. Also the timestamps that have a Planck-scale level of decimal precision have to be truncated to bring them back out of the quantum mechanics realm. Logstash's string coercion turns them to scientific notation otherwise.

So I think it's really unnecessary to preserve the numeric typing in JSON output. Unless, for some reason that I can't imagine, you need to do arithmetic operations on your fields, I would say that most post-processing backends will prefer to work with strings. I don't believe this is particular to Logstash. It's generally easier to pass a string to the backend (for example Elasticsearch) and tell it that the string is a numeric than it is to build in exception handing for numerics that ultimately end up being stored as strings. This is especially difficult when fields randomly show up with an unexpected type constraint, as happens in evtx.

My current workaround is to force conversion of all numerics to strings using `jq` but I hope that one day this extra step will be eliminated.

**Comment by scudette** [comment] 2019-11-26 22:58
Heh I think this is the main reason I moved away from go-evtx - its really hard to process fields when you dont know their types. For example timestamps need to be floats otherwise you just can not present them as a proper time. It got really tedious to manually convert everything from strings. 

I think JSON hits its limitations quickly - for example it has no way to store int64 so it becomes a string anyway - technically everything is float (no ints anyway). So the issue is really about json encoding. So we are always going to have problems when moving data through json from one system to another. This is why logstash/elastic just serialize to string and hope for the best (presumably the index tells it how to handle the string properly - as long as your index is not autodefined :-).

I dont mind having a parser option that does this but obviously it wont be appropriate in Velociraptor because the VQL needs to get the proper types (and it has no inherent json limitations).

**Comment by predictiple** [comment] 2019-11-27 04:42
hmmm when data is produced and then consumed by VQL the preservation of types makes sense because it's then an "internal" data exchange. If the data is produced for external consumption then it needs to be as consumer-friendly as possible. So maybe, as you suggest, a parser option for when VQL is not being used.

If we look at other tools - not just evtx parsers - we don't see many of them presenting astronomical-scale numbers in numerically typed form, hence the stringified hex we see in Windows event viewer for fields like `Keywords`. I'm also quite suspicious of that float representation of the timestamp - I don't think there are any clocks in the world that have that level of precision, so I wonder what Windows is basing it on?

I would still argue that Microsoft is storing values as numerics for the purpose of saving storage space rather than for semantic reasons. As I've mentioned before, things like EventId are actually labels that just happen to be composed of digits, but EventID=suwkjhz would be equally meaningful.

**Comment by scudette** [comment] 2019-11-27 05:05
Not at all. Event id is an index into a message table and therefore it is
an integer. It is in fact used as an index when we locate the message table
in the dll. And similarly used as an integer when looking it up in the
message db. We can of course covert back and forth to string as required.

I think this issue is more about the inadequate serialization capability of
json to represent large or small values. I actually don't think elastic
stores everything as string either, the index defines it's schema
accurately, and elastic converts back and forth as required.

**Comment by predictiple** [comment] 2019-11-27 05:19
Indexes can be strings too. Microsoft could have used the EventID "rexthedog" instead of 4624 but they didn't do so because alphabetic strings carry with them unintentional meanings. EventIDs are composed of digits purely as a convention, and that was done because they wanted to imply some relations by associating IDs in certain numeric ranges. But they could just have easily said that all event IDs starting with "cat" are logon events. 

> I think this issue is more about the inadequate serialization capability of
json to represent large or small values. I actually don't think elastic
stores everything as string either, the index defines it's schema
accurately, and elastic converts back and forth as required.

yes, and the workaround in an industry awash with JSON is to not really use/rely on JSON typing because of it's limitations.

**Comment by scudette** [comment] 2020-11-01 23:40
I don't think there is anything here for us to do. Closing as WAI

**Closed by scudette** 2020-11-01 23:40 UTC
